import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requireAdmin } from "@/lib/auth";
import { logoutAction, savePlanAction } from "@/app/admin/actions";
export const dynamic = "force-dynamic";
export default async function MembershipAdmin({ searchParams }: { searchParams: Promise<{ result?: string }> }) {
  await requireAdmin();
  const [{ result }, plans] = await Promise.all([searchParams, prisma.membershipPlan.findMany({ include: { features: { orderBy: { position: "asc" } } }, orderBy: { createdAt: "desc" } }).catch(() => [])]);
  return <main className="admin-page"><aside className="admin-sidebar"><Link href="/" className="brand"><span className="brand-mark">♞</span>CHESS<span className="cyan">254</span></Link><div className="admin-label">CONTROL ROOM</div><Link href="/admin">Overview</Link><Link className="admin-active" href="/admin/memberships">Membership plans</Link><form action={logoutAction}><button className="logout-button">Sign out ↗</button></form></aside><section className="admin-main"><Link href="/admin" className="arrow-link">← Overview</Link><div className="section-kicker admin-kicker">CONTENT / MEMBERSHIPS</div><h1>Membership<br/><span>plans.</span></h1>{result === "saved" && <div className="notice success">Plan created.</div>}{result === "invalid" && <div className="notice">Some fields were invalid.</div>}{result === "error" && <div className="notice">Could not create the plan. Check that the slug is unique.</div>}<div className="admin-plan-layout"><div className="admin-plan-list"><h2>Existing plans</h2>{plans.length ? plans.map((p) => <article key={p.id}><div><strong>{p.name}</strong><span>{p.status} · {p.billingPeriod}</span></div><b>{p.currency} {Number(p.price).toLocaleString("en-KE")}</b><p>{p.description}</p></article>) : <p className="admin-note">No membership plans yet. Add the first plan here.</p>}</div><div className="form-panel"><h2>Create a plan</h2><form action={savePlanAction} className="contact-form"><label>Name<input name="name" required maxLength={100}/></label><label>Slug<input name="slug" required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={120}/></label><label>Description<textarea name="description" required minLength={10} maxLength={2000}/></label><div className="form-inline"><label>Price<input type="number" name="price" min="0" step="0.01" required/></label><label>Currency<input name="currency" defaultValue="KES" minLength={3} maxLength={3} required/></label></div><label>Billing period<select name="billingPeriod"><option value="MONTHLY">Monthly</option><option value="QUARTERLY">Quarterly</option><option value="ANNUAL">Annual</option><option value="LIFETIME">Lifetime</option></select></label><label>Benefits <span>(one per line)</span><textarea name="features" rows={4}/></label><label>Status<select name="status"><option value="DRAFT">Draft</option><option value="ACTIVE">Active</option></select></label><button type="submit" className="button">Create plan <span>↗</span></button></form></div></div></section></main>;
}
