import Image from "next/image";
import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, MoveUpRight } from "lucide-react";
import { getHomeContent, settingText } from "@/lib/content";

export const dynamic = "force-dynamic";

const money = (amount: { toString(): string }, currency: string) => new Intl.NumberFormat("en-KE", { style: "currency", currency, maximumFractionDigits: 0 }).format(Number(amount));

export default async function Home() {
  const { plans, events, photos, announcement, settings } = await getHomeContent();
  const club = settingText(settings, "club.name", "Chess254");
  const tagline = settingText(settings, "club.tagline", "Make your next move.");
  const location = settingText(settings, "club.location", "Westlands · Nairobi");

  return <main>
    <header className="nav"><Link href="/" className="brand" aria-label="Chess254 home"><span className="brand-mark">♞</span><span>CHESS<span className="cyan">254</span></span></Link><nav className="nav-links"><a href="#clubhouse">The clubhouse</a><a href="#membership">Membership</a><a href="#calendar">What’s on</a><Link href="/learn">Learn</Link><Link href="/account/login">Sign in</Link></nav><Link href="/join" className="button button-small">Join the club <ArrowUpRight size={15}/></Link></header>
    {announcement && <a className="announcement" href="#calendar"><span className="pulse"/>{announcement.title}<span>{announcement.body}</span><ArrowUpRight size={14}/></a>}
    <section className="hero" id="clubhouse">
      <div className="hero-content"><div className="eyebrow"><span className="eyebrow-line"/> {location}</div><h1>{tagline.split(" ").slice(0, -2).join(" ")}<br/><span>{tagline.split(" ").slice(-2).join(" ")}</span></h1><p className="hero-copy">{settingText(settings, "home.heroBody", "Club information will appear here once configured.")}</p><div className="hero-actions"><Link href="/join" className="button">Find your place <ArrowUpRight size={17}/></Link><a href="#clubhouse-story" className="text-link">Explore the clubhouse <ArrowDownRight size={16}/></a></div><div className="hero-foot"><div className="live-dot"/>A club for every kind of player <span className="foot-divider"/>{location}</div></div>
      <div className="hero-image"><Image src="/githinji.jpg" alt="Chess player studying a position at the board" fill priority sizes="(max-width: 800px) 100vw, 52vw" className="cover-image"/><div className="image-shade"/><div className="image-caption"><span className="caption-number">01 / 04</span><span>Every move has a story.</span><span className="caption-symbol">♞</span></div><div className="vertical-label">PLAY · LEARN · BELONG</div></div>
      <div className="hero-side-note">EST. IN NAIROBI <span>♜</span></div>
    </section>
    <div className="ticker"><div>GOOD CHESS. GOOD PEOPLE. GOOD ENERGY. <span>♞</span> GOOD CHESS. GOOD PEOPLE. GOOD ENERGY. <span>♞</span> GOOD CHESS. GOOD PEOPLE. GOOD ENERGY. <span>♞</span></div></div>
    <section className="intro section" id="clubhouse-story"><div className="section-kicker">01 — MORE THAN A GAME</div><div className="intro-grid"><h2>The board is<br/>just the <em>beginning.</em></h2><div className="intro-copy"><p>{club} brings Nairobi’s chess community together around one table. Come for a game, stay for the conversations, coaching, and the friendships that happen between moves.</p><Link href="/about" className="arrow-link">Meet your clubhouse <MoveUpRight size={16}/></Link></div></div><div className="values"><article><span>01</span><h3>Play with purpose</h3><p>Casual games, competitive sessions, and room to find your level.</p></article><article><span>02</span><h3>Grow your game</h3><p>Learn with coaches and players who want to see you improve.</p></article><article><span>03</span><h3>Find your people</h3><p>A welcoming community that makes every visit feel familiar.</p></article></div></section>
    <section className="membership section" id="membership"><div className="membership-head"><div><div className="section-kicker">02 — FIND YOUR GAME</div><h2>Your seat at<br/>the <em>table.</em></h2></div><p>Choose the way you want to play. Every membership is managed by the club and built around your chess life.</p></div>{plans.length ? <div className="plan-grid">{plans.map((plan, index) => <article className={`plan-card ${index === 0 ? "plan-featured" : ""}`} key={plan.id}><div className="plan-top"><span>{plan.billingPeriod.toLowerCase()}</span><span className="plan-arrow"><ArrowUpRight size={17}/></span></div><h3>{plan.name}</h3><p>{plan.description}</p><div className="plan-price">{money(plan.price, plan.currency)}<span> / {plan.billingPeriod.toLowerCase()}</span></div><ul>{plan.features.map((feature) => <li key={feature.id}><span>↗</span>{feature.label}</li>)}</ul><Link href={`/join?plan=${plan.slug}`} className="button plan-button">Choose membership <ArrowUpRight size={15}/></Link></article>)}</div> : <div className="empty-state"><span>♞</span><h3>Memberships are being set up.</h3><p>Check back soon for ways to join the clubhouse.</p></div>}</section>
    <section className="events section" id="calendar"><div className="events-head"><div><div className="section-kicker">03 — AROUND THE CLUB</div><h2>Make a date<br/>with the <em>board.</em></h2></div><Link href="/events" className="arrow-link">All events <MoveUpRight size={16}/></Link></div>{events.length ? <div className="event-list">{events.map((event) => <Link href={`/events/${event.slug}`} className="event-row" key={event.id}><div className="event-date"><span>{event.startsAt.toLocaleDateString("en-KE", { month: "short" }).toUpperCase()}</span><strong>{event.startsAt.toLocaleDateString("en-KE", { day: "2-digit" })}</strong></div><div className="event-main"><h3>{event.title}</h3><p>{event.location || "Clubhouse"}</p></div><span className="event-time">{event.startsAt.toLocaleTimeString("en-KE", { hour: "numeric", minute: "2-digit" })}</span><span className="event-price">{Number(event.price) ? money(event.price, event.currency) : "Free"}</span><ArrowUpRight size={18}/></Link>)}</div> : <div className="empty-state"><span>♜</span><h3>No upcoming events</h3><p>There are no events on the calendar right now. Check back for the next one.</p></div>}</section>
    <section className="gallery section"><div className="gallery-head"><div><div className="section-kicker">04 — THE CLUBHOUSE IN MOTION</div><h2>Good moves.<br/><em>Better company.</em></h2></div><Link href="/gallery" className="arrow-link">Explore the gallery <MoveUpRight size={16}/></Link></div>{photos.length ? <div className="gallery-grid">{photos.map((photo) => <figure key={photo.id}><div className="gallery-photo"><Image src={photo.imageUrl} alt={photo.title} fill sizes="(max-width: 700px) 100vw, 33vw"/></div><figcaption>{photo.title}<span>{photo.category}</span></figcaption></figure>)}</div> : <div className="empty-state gallery-empty"><span>▧</span><h3>The gallery is waiting for its first story.</h3><p>Club moments will appear here as they’re added.</p></div>}</section>
    <section className="closing"><div className="closing-mark">♞</div><div className="section-kicker">YOUR NEXT MOVE STARTS HERE</div><h2>Pull up<br/>a <em>chair.</em></h2><p>New to chess or ready for your next tournament. There’s room for you here.</p><Link href="/join" className="button">Join {club} <ArrowUpRight size={16}/></Link><span className="closing-watermark">♞</span></section>
    <footer><Link href="/" className="brand"><span className="brand-mark">♞</span><span>CHESS<span className="cyan">254</span></span></Link><span>{location}</span><div><Link href="/contact">Get in touch</Link><Link href="/about">About</Link><Link href="/account/login">Member sign in</Link></div><span>© {new Date().getFullYear()} {club}</span></footer>
  </main>;
}
